name: 'servidores_recife'
version: '1.0.0'
config-version: 2

profile: 'servidores_recife'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  servidores_recife:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: servidores_elt